Adds support for PHP 8.1
laminas/laminas-navigation pull request #26
Opened 2021-12-03 10:58 UTC by froschdesign

|    Q          |   A
|-------------- | ------
| Enhancement | yes

Fixes #25

2021-12-03 11:36 UTC, Ocramius requested changes

2021-12-03 11:36 UTC, Ocramius commented on composer.json
> +        "php": "^7.3 || ~8.0.0 || ~8.1.0",
We can bump to `^7.4` here

2021-12-03 11:38 UTC, froschdesign commented on composer.json
> +        "php": "^7.3 || ~8.0.0 || ~8.1.0",
Is planned 👍

2021-12-06 01:41 UTC, Ocramius commented
A rebase + `composer.lock` update (for the lowest PHP version) is needed here

2021-12-07 04:12 UTC, Ocramius approved these changes
LGTM. @froschdesign what should we do about PHPCS failures? :thinking:

2021-12-07 08:50 UTC, froschdesign commented
@Ocramius 
> …what should we do about PHPCS failures?

I will solve the problem but no hurry, because PHP 8.1 itself is [not yet ready](https://github.com/php/doc-en/issues/980). 😜

2021-12-12 11:14 UTC, fezfez commented
can be merge ?

2021-12-12 19:57 UTC, Ocramius approved these changes
Yep! 🚢 

Thanks @froschdesign!

2021-12-12 19:57 UTC, merged

2021-12-12 19:59 UTC, samsonasik commented
@Ocramius should it be merged to 2.13.x branch?